apiVersion: v1
kind: Service
metadata:
  name: ms-ticket-service
  labels:
    app: ms-ticket
spec:
  selector:
    app: ms-ticket
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
